LOCK TABLE "Role" IN EXCLUSIVE MODE;
 INSERT INTO "Role" ("idroles", "role", "discritption") VALUES (DEFAULT,'Super Admin','Full access to all functions');
 INSERT INTO "Role" ("idroles", "role", "discritption") VALUES (DEFAULT,'Admin','Admin functions only can not create applications');
 INSERT INTO "Role" ("idroles", "role", "discritption") VALUES (DEFAULT,'Applicant','Can only create application');
 INSERT INTO "Role" ("idroles", "role", "discritption") VALUES (DEFAULT,'Authorisor','Can authorise applications');
 INSERT INTO "Role" ("idroles", "role", "discritption") VALUES (DEFAULT,'Test','No login required');
LOCK TABLE "Task" IN EXCLUSIVE MODE;
 INSERT INTO "Task" ("idtasks", "task", "description") VALUES (DEFAULT,'Application','Travel application');
 INSERT INTO "Task" ("idtasks", "task", "description") VALUES (DEFAULT,'Authorise','Authorise travel applications');
 INSERT INTO "Task" ("idtasks", "task", "description") VALUES (DEFAULT,'Attach','Attach document');
 INSERT INTO "Task" ("idtasks", "task", "description") VALUES (DEFAULT,'User','CRUD users');
LOCK TABLE "Account" IN EXCLUSIVE MODE;
 INSERT INTO "Account" ("idAccount", "Account", "Password", "Salt", "DateCreated", "DateLogin") VALUES (DEFAULT,'superadmin','super','1','0000-00-00 00:00:00','0000-00-00 00:00:00');
 INSERT INTO "Account" ("idAccount", "Account", "Password", "Salt", "DateCreated", "DateLogin") VALUES (DEFAULT,'admin','admin','1','0000-00-00 00:00:00','0000-00-00 00:00:00');
 INSERT INTO "Account" ("idAccount", "Account", "Password", "Salt", "DateCreated", "DateLogin") VALUES (DEFAULT,'testapplicant','test','1','0000-00-00 00:00:00','0000-00-00 00:00:00');
 INSERT INTO "Account" ("idAccount", "Account", "Password", "Salt", "DateCreated", "DateLogin") VALUES (DEFAULT,'testauthoriser','test','1','0000-00-00 00:00:00','0000-00-00 00:00:00');
LOCK TABLE "AccountRole" IN EXCLUSIVE MODE;
 INSERT INTO "AccountRole" ("idUserRoles", "AccountID", "RoleID") VALUES (DEFAULT,1,1);
 INSERT INTO "AccountRole" ("idUserRoles", "AccountID", "RoleID") VALUES (DEFAULT,2,2);
 INSERT INTO "AccountRole" ("idUserRoles", "AccountID", "RoleID") VALUES (DEFAULT,3,5);
LOCK TABLE "Permission" IN EXCLUSIVE MODE;
LOCK TABLE "Session" IN EXCLUSIVE MODE;
LOCK TABLE "TravelerProfile" IN EXCLUSIVE MODE;
 INSERT INTO "TravelerProfile" ("idTravelerProfile", "AccountID", "GivenName", "FamilyName", "Title", "Department", "Position", "TravelBooker", "IDnumber", "BusinessAddress", "BusinessPhone", "BusinessFax", "BusinessEmail", "HomeAddress", "HomePhone", "HomeEmail", "MobilePhone", "SpouseName", "SpouseContactNumber", "SpouseEmail", "DoctorsName", "DoctorsConctactNumber", "DoctorsEmail", "KnownMedicalConditions", "AttachmentID", "DateCreated", "DateModified") VALUES (DEFAULT,3,'Test','Test','Test',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
LOCK TABLE "TravelDocument" IN EXCLUSIVE MODE;
