--INSERT INTO CURRENCY VALUES ('countryname','currencyname','code2','code3','currencycode3');
-- cat ./iso-country-2\&3-cur.csv | sed -e "s/.*/INSERT INTO "CURRENCY" VALUES (&);/" >> ./mtams-worlddb.data.javadb.sql

INSERT INTO CURRENCY VALUES ('Andorra','Euro','AD','AND','EUR');
INSERT INTO CURRENCY VALUES ('United Arab Emirates','UAE Dirham','AE','ARE','AED');
INSERT INTO CURRENCY VALUES ('Afghanistan','Afghani','AF','AFG','AFN');
INSERT INTO CURRENCY VALUES ('Antigua and Barbuda','East Caribbean Dollar','AG','ATG','XCD');
INSERT INTO CURRENCY VALUES ('Anguilla','East Caribbean Dollar','AI','AIA','XCD');
INSERT INTO CURRENCY VALUES ('Albania','Lek','AL','ALB','ALL');
INSERT INTO CURRENCY VALUES ('Armenia','Armenian Dram','AM','ARM','AMD');
INSERT INTO CURRENCY VALUES ('Angola','Kwanza','AO','AGO','AOA');
INSERT INTO CURRENCY VALUES ('Argentina','Argentine Peso','AR','ARG','ARS');
INSERT INTO CURRENCY VALUES ('American Samoa','US Dollar','AS','ASM','USD');
INSERT INTO CURRENCY VALUES ('Austria','Euro','AT','AUT','EUR');
INSERT INTO CURRENCY VALUES ('Australia','Australian Dollar','AU','AUS','AUD');
INSERT INTO CURRENCY VALUES ('Aruba','Aruban Florin','AW','ABW','AWG');
INSERT INTO CURRENCY VALUES ('Åland Islands','Euro','AX','ALA','EUR');
INSERT INTO CURRENCY VALUES ('Azerbaijan','Azerbaijanian Manat','AZ','AZE','AZN');
INSERT INTO CURRENCY VALUES ('Bosnia and Herzegovina','Convertible Mark','BA','BIH','BAM');
INSERT INTO CURRENCY VALUES ('Barbados','Barbados Dollar','BB','BRB','BBD');
INSERT INTO CURRENCY VALUES ('Bangladesh','Taka','BD','BGD','BDT');
INSERT INTO CURRENCY VALUES ('Belgium','Euro','BE','BEL','EUR');
INSERT INTO CURRENCY VALUES ('Burkina Faso','CFA Franc BCEAO','BF','BFA','XOF');
INSERT INTO CURRENCY VALUES ('Bulgaria','Bulgarian Lev','BG','BGR','BGN');
INSERT INTO CURRENCY VALUES ('Bahrain','Bahraini Dinar','BH','BHR','BHD');
INSERT INTO CURRENCY VALUES ('Burundi','Burundi Franc','BI','BDI','BIF');
INSERT INTO CURRENCY VALUES ('Benin','CFA Franc BCEAO','BJ','BEN','XOF');
INSERT INTO CURRENCY VALUES ('Saint Barthélemy','Euro','BL','BLM','EUR');
INSERT INTO CURRENCY VALUES ('Bermuda','Bermudian Dollar','BM','BMU','BMD');
INSERT INTO CURRENCY VALUES ('Brunei Darussalam','Brunei Dollar','BN','BRN','BND');
INSERT INTO CURRENCY VALUES ('Bolivia, Plurinational State Of','Boliviano','BO','BOL','BOB');
INSERT INTO CURRENCY VALUES ('Bolivia, Plurinational State Of','Mvdol','BO','BOL','BOV');
INSERT INTO CURRENCY VALUES ('Bonaire, Sint Eustatius and Saba','US Dollar','BQ','BES','USD');
INSERT INTO CURRENCY VALUES ('Brazil','Brazilian Real','BR','BRA','BRL');
INSERT INTO CURRENCY VALUES ('Bahamas','Bahamian Dollar','BS','BHS','BSD');
INSERT INTO CURRENCY VALUES ('Bhutan','Ngultrum','BT','BTN','BTN');
INSERT INTO CURRENCY VALUES ('Bhutan','Indian Rupee','BT','BTN','INR');
INSERT INTO CURRENCY VALUES ('Bouvet Island','Norwegian Krone','BV','BVT','NOK');
INSERT INTO CURRENCY VALUES ('Botswana','Pula','BW','BWA','BWP');
INSERT INTO CURRENCY VALUES ('Belarus','Belarussian Ruble','BY','BLR','BYR');
INSERT INTO CURRENCY VALUES ('Belize','Belize Dollar','BZ','BLZ','BZD');
INSERT INTO CURRENCY VALUES ('Canada','Canadian Dollar','CA','CAN','CAD');
INSERT INTO CURRENCY VALUES ('Cocos (Keeling) Islands','Australian Dollar','CC','CCK','AUD');
INSERT INTO CURRENCY VALUES ('Congo, The Democratic Republic Of The','Congolais Franc','CD','COD','CDF');
INSERT INTO CURRENCY VALUES ('Central African Republic','CFA Franc BEAC','CF','CAF','XAF');
INSERT INTO CURRENCY VALUES ('Congo','CFA Franc BEAC','CG','COG','XAF');
INSERT INTO CURRENCY VALUES ('Switzerland','WIR Euro','CH','CHE','CHE');
INSERT INTO CURRENCY VALUES ('Switzerland','Swiss Franc','CH','CHE','CHF');
INSERT INTO CURRENCY VALUES ('Switzerland','WIR Franc','CH','CHE','CHW');
INSERT INTO CURRENCY VALUES ('Côte D''Ivoire','CFA Franc BCEAO','CI','CIV','XOF');
INSERT INTO CURRENCY VALUES ('Cook Islands','New Zealand Dollar','CK','COK','NZD');
INSERT INTO CURRENCY VALUES ('Chile','Unidades de fomento','CL','CHL','CLF');
INSERT INTO CURRENCY VALUES ('Chile','Chilean Peso','CL','CHL','CLP');
INSERT INTO CURRENCY VALUES ('Cameroon','CFA Franc BEAC','CM','CMR','XAF');
INSERT INTO CURRENCY VALUES ('China','Yuan Renminbi','CN','CHN','CNY');
INSERT INTO CURRENCY VALUES ('Colombia','Colombian Peso','CO','COL','COP');
INSERT INTO CURRENCY VALUES ('Colombia','Unidad de Valor real','CO','COL','COU');
INSERT INTO CURRENCY VALUES ('Costa Rica','Costa Rican Colon','CR','CRI','CRC');
INSERT INTO CURRENCY VALUES ('Cuba','Peso Convertible','CU','CUB','CUC');
INSERT INTO CURRENCY VALUES ('Cuba','Cuban Peso','CU','CUB','CUP');
INSERT INTO CURRENCY VALUES ('Cape Verde','Cape Verde Escudo','CV','CPV','CVE');
INSERT INTO CURRENCY VALUES ('Curaçao','Netherlands Antillean Guilder','CW','CUW','ANG');
INSERT INTO CURRENCY VALUES ('Christmas Island','Australian Dollar','CX','CXR','AUD');
INSERT INTO CURRENCY VALUES ('Cyprus','Euro','CY','CYP','EUR');
INSERT INTO CURRENCY VALUES ('Czech Republic','Czech Koruna','CZ','CZE','CZK');
INSERT INTO CURRENCY VALUES ('Germany','Euro','DE','DEU','EUR');
INSERT INTO CURRENCY VALUES ('Djibouti','Djibouti Franc','DJ','DJI','DJF');
INSERT INTO CURRENCY VALUES ('Denmark','Danish Krone','DK','DNK','DKK');
INSERT INTO CURRENCY VALUES ('Dominica','East Caribbean Dollar','DM','DMA','XCD');
INSERT INTO CURRENCY VALUES ('Dominican Republic','Dominican Peso','DO','DOM','DOP');
INSERT INTO CURRENCY VALUES ('Algeria','Algerian Dinar','DZ','DZA','DZD');
INSERT INTO CURRENCY VALUES ('Ecuador','US Dollar','EC','ECU','USD');
INSERT INTO CURRENCY VALUES ('Estonia','Euro','EE','EST','EUR');
INSERT INTO CURRENCY VALUES ('Egypt','Egyptian Pound','EG','EGY','EGP');
INSERT INTO CURRENCY VALUES ('Western Sahara','Moroccan Dirham','EH','ESH','MAD');
INSERT INTO CURRENCY VALUES ('Eritrea','Nakfa','ER','ERI','ERN');
INSERT INTO CURRENCY VALUES ('Spain','Euro','ES','ESP','EUR');
INSERT INTO CURRENCY VALUES ('Ethiopia','Ethiopian Birr','ET','ETH','ETB');
INSERT INTO CURRENCY VALUES ('Finland','Euro','FI','FIN','EUR');
INSERT INTO CURRENCY VALUES ('Fiji','Fiji Dollar','FJ','FJI','FJD');
INSERT INTO CURRENCY VALUES ('Falkland Islands (Malvinas)','Falkland Islands Pound','FK','FLK','FKP');
INSERT INTO CURRENCY VALUES ('Micronesia, Federated States Of','US Dollar','FM','FSM','USD');
INSERT INTO CURRENCY VALUES ('Faroe Islands','Danish Krone','FO','FRO','DKK');
INSERT INTO CURRENCY VALUES ('France','Euro','FR','FRA','EUR');
INSERT INTO CURRENCY VALUES ('Gabon','CFA Franc BEAC','GA','GAB','XAF');
INSERT INTO CURRENCY VALUES ('United Kingdom','Pound Sterling','GB','GBR','GBP');
INSERT INTO CURRENCY VALUES ('Grenada','East Caribbean Dollar','GD','GRD','XCD');
INSERT INTO CURRENCY VALUES ('Georgia','Lari','GE','GEO','GEL');
INSERT INTO CURRENCY VALUES ('French Guiana','Euro','GF','GUF','EUR');
INSERT INTO CURRENCY VALUES ('Guernsey','Pound Sterling','GG','GGY','GBP');
INSERT INTO CURRENCY VALUES ('Ghana','Ghana Cedi','GH','GHA','GHS');
INSERT INTO CURRENCY VALUES ('Gibraltar','Gibraltar Pound','GI','GIB','GIP');
INSERT INTO CURRENCY VALUES ('Greenland','Danish Krone','GL','GRL','DKK');
INSERT INTO CURRENCY VALUES ('Gambia','Dalasi','GM','GMB','GMD');
INSERT INTO CURRENCY VALUES ('Guinea','Guinea Franc','GN','GIN','GNF');
INSERT INTO CURRENCY VALUES ('Guadeloupe','Euro','GP','GLP','EUR');
INSERT INTO CURRENCY VALUES ('Equatorial Guinea','CFA Franc BEAC','GQ','GNQ','XAF');
INSERT INTO CURRENCY VALUES ('Greece','Euro','GR','GRC','EUR');
INSERT INTO CURRENCY VALUES ('Guatemala','Quetzal','GT','GTM','GTQ');
INSERT INTO CURRENCY VALUES ('Guam','US Dollar','GU','GUM','USD');
INSERT INTO CURRENCY VALUES ('Guinea-Bissau','CFA Franc BCEAO','GW','GNB','XOF');
INSERT INTO CURRENCY VALUES ('Guyana','Guyana Dollar','GY','GUY','GYD');
INSERT INTO CURRENCY VALUES ('Hong Kong','Hong Kong Dollar','HK','HKG','HKD');
INSERT INTO CURRENCY VALUES ('Heard Island and McDonald Islands','Australian Dollar','HM','HMD','AUD');
INSERT INTO CURRENCY VALUES ('Honduras','Lempira','HN','HND','HNL');
INSERT INTO CURRENCY VALUES ('Croatia','Croatian Kuna','HR','HRV','HRK');
INSERT INTO CURRENCY VALUES ('Haiti','Gourde','HT','HTI','HTG');
INSERT INTO CURRENCY VALUES ('Haiti','US Dollar','HT','HTI','USD');
INSERT INTO CURRENCY VALUES ('Hungary','Forint','HU','HUN','HUF');
INSERT INTO CURRENCY VALUES ('Indonesia','Rupiah','ID','IDN','IDR');
INSERT INTO CURRENCY VALUES ('Ireland','Euro','IE','IRL','EUR');
INSERT INTO CURRENCY VALUES ('Israel','New Israeli Sheqel','IL','ISR','ILS');
INSERT INTO CURRENCY VALUES ('Isle of Man','Pound Sterling','IM','IMN','GBP');
INSERT INTO CURRENCY VALUES ('India','Indian Rupee','IN','IND','INR');
INSERT INTO CURRENCY VALUES ('British Indian Ocean Territory','US Dollar','IO','IOT','USD');
INSERT INTO CURRENCY VALUES ('Iraq','Iraqi Dinar','IQ','IRQ','IQD');
INSERT INTO CURRENCY VALUES ('Iran, Islamic Republic Of','Iranian Rial','IR','IRN','IRR');
INSERT INTO CURRENCY VALUES ('Iceland','Iceland Krona','IS','ISL','ISK');
INSERT INTO CURRENCY VALUES ('Italy','Euro','IT','ITA','EUR');
INSERT INTO CURRENCY VALUES ('Jersey','Pound Sterling','JE','JEY','GBP');
INSERT INTO CURRENCY VALUES ('Jamaica','Jamaican Dollar','JM','JAM','JMD');
INSERT INTO CURRENCY VALUES ('Jordan','Jordanian Dinar','JO','JOR','JOD');
INSERT INTO CURRENCY VALUES ('Japan','Yen','JP','JPN','JPY');
INSERT INTO CURRENCY VALUES ('Kenya','Kenyan Shilling','KE','KEN','KES');
INSERT INTO CURRENCY VALUES ('Kyrgyzstan','Som','KG','KGZ','KGS');
INSERT INTO CURRENCY VALUES ('Cambodia','Riel','KH','KHM','KHR');
INSERT INTO CURRENCY VALUES ('Kiribati','Australian Dollar','KI','KIR','AUD');
INSERT INTO CURRENCY VALUES ('Comoros','Comoro Franc','KM','COM','KMF');
INSERT INTO CURRENCY VALUES ('Saint Kitts And Nevis','East Caribbean Dollar','KN','KNA','XCD');
INSERT INTO CURRENCY VALUES ('Korea, Democratic People''s Republic Of','North Korean Won','KP','PRK','KPW');
INSERT INTO CURRENCY VALUES ('Korea, Republic of','Won','KR','KOR','KRW');
INSERT INTO CURRENCY VALUES ('Kuwait','Kuwaiti Dinar','KW','KWT','KWD');
INSERT INTO CURRENCY VALUES ('Cayman Islands','Cayman Islands Dollar','KY','CYM','KYD');
INSERT INTO CURRENCY VALUES ('Kazakhstan','Tenge','KZ','KAZ','KZT');
INSERT INTO CURRENCY VALUES ('Lao People''s Democratic Republic','Kip','LA','LAO','LAK');
INSERT INTO CURRENCY VALUES ('Lebanon','Lebanese Pound','LB','LBN','LBP');
INSERT INTO CURRENCY VALUES ('Saint Lucia','East Caribbean Dollar','LC','LCA','XCD');
INSERT INTO CURRENCY VALUES ('Liechtenstein','Swiss Franc','LI','LIE','CHF');
INSERT INTO CURRENCY VALUES ('Sri Lanka','Sri Lanka Rupee','LK','LKA','LKR');
INSERT INTO CURRENCY VALUES ('Liberia','Liberian Dollar','LR','LBR','LRD');
INSERT INTO CURRENCY VALUES ('Lesotho','Loti','LS','LSO','LSL');
INSERT INTO CURRENCY VALUES ('Lesotho','Rand','LS','LSO','ZAR');
INSERT INTO CURRENCY VALUES ('Lithuania','Lithuanian Litas','LT','LTU','LTL');
INSERT INTO CURRENCY VALUES ('Luxembourg','Euro','LU','LUX','EUR');
INSERT INTO CURRENCY VALUES ('Latvia','Latvian Lats','LV','LVA','LVL');
INSERT INTO CURRENCY VALUES ('Libya','Libyan Dinar','LY','LBY','LYD');
INSERT INTO CURRENCY VALUES ('Morocco','Moroccan Dirham','MA','MAR','MAD');
INSERT INTO CURRENCY VALUES ('Monaco','Euro','MC','MCO','EUR');
INSERT INTO CURRENCY VALUES ('Moldova, Republic of','Moldovan Leu','MD','MDA','MDL');
INSERT INTO CURRENCY VALUES ('Montenegro','Euro','ME','MNE','EUR');
INSERT INTO CURRENCY VALUES ('Saint Martin (French Part)','Euro','MF','MAF','EUR');
INSERT INTO CURRENCY VALUES ('Madagascar','Malagasy Ariary','MG','MDG','MGA');
INSERT INTO CURRENCY VALUES ('Marshall Islands','US Dollar','MH','MHL','USD');
INSERT INTO CURRENCY VALUES ('Macedonia, the Former Yugoslav Republic Of','Denar','MK','MKD','MKD');
INSERT INTO CURRENCY VALUES ('Mali','CFA Franc BCEAO','ML','MLI','XOF');
INSERT INTO CURRENCY VALUES ('Myanmar','Kyat','MM','MMR','MMK');
INSERT INTO CURRENCY VALUES ('Mongolia','Tugrik','MN','MNG','MNT');
INSERT INTO CURRENCY VALUES ('Macao','Pataca','MO','MAC','MOP');
INSERT INTO CURRENCY VALUES ('Northern Mariana Islands','US Dollar','MP','MNP','USD');
INSERT INTO CURRENCY VALUES ('Martinique','Euro','MQ','MTQ','EUR');
INSERT INTO CURRENCY VALUES ('Mauritania','Ouguiya','MR','MRT','MRO');
INSERT INTO CURRENCY VALUES ('Montserrat','East Caribbean Dollar','MS','MSR','XCD');
INSERT INTO CURRENCY VALUES ('Malta','Euro','MT','MLT','EUR');
INSERT INTO CURRENCY VALUES ('Mauritius','Mauritius Rupee','MU','MUS','MUR');
INSERT INTO CURRENCY VALUES ('Maldives','Rufiyaa','MV','MDV','MVR');
INSERT INTO CURRENCY VALUES ('Malawi','Kwacha','MW','MWI','MWK');
INSERT INTO CURRENCY VALUES ('Mexico','Mexican Peso','MX','MEX','MXN');
INSERT INTO CURRENCY VALUES ('Mexico','Mexican Unidad de Inversion (UDI)','MX','MEX','MXV');
INSERT INTO CURRENCY VALUES ('Malaysia','Malaysian Ringgit','MY','MYS','MYR');
INSERT INTO CURRENCY VALUES ('Mozambique','Mozambique Metical','MZ','MOZ','MZN');
INSERT INTO CURRENCY VALUES ('Namibia','Namibia Dollar','NA','NAM','NAD');
INSERT INTO CURRENCY VALUES ('Namibia','Rand','NA','NAM','ZAR');
INSERT INTO CURRENCY VALUES ('New Caledonia','CFP Franc','NC','NCL','XPF');
INSERT INTO CURRENCY VALUES ('Niger','CFA Franc BCEAO','NE','NER','XOF');
INSERT INTO CURRENCY VALUES ('Norfolk Island','Australian Dollar','NF','NFK','AUD');
INSERT INTO CURRENCY VALUES ('Nigeria','Naira','NG','NGA','NGN');
INSERT INTO CURRENCY VALUES ('Nicaragua','Cordoba Oro','NI','NIC','NIO');
INSERT INTO CURRENCY VALUES ('Netherlands','Euro','NL','NLD','EUR');
INSERT INTO CURRENCY VALUES ('Norway','Norwegian Krone','NO','NOR','NOK');
INSERT INTO CURRENCY VALUES ('Nepal','Nepalese Rupee','NP','NPL','NPR');
INSERT INTO CURRENCY VALUES ('Nauru','Australian Dollar','NR','NRU','AUD');
INSERT INTO CURRENCY VALUES ('Niue','New Zealand Dollar','NU','NIU','NZD');
INSERT INTO CURRENCY VALUES ('New Zealand','New Zealand Dollar','NZ','NZL','NZD');
INSERT INTO CURRENCY VALUES ('Oman','Rial Omani','OM','OMN','OMR');
INSERT INTO CURRENCY VALUES ('Panama','Balboa','PA','PAN','PAB');
INSERT INTO CURRENCY VALUES ('Panama','US Dollar','PA','PAN','USD');
INSERT INTO CURRENCY VALUES ('Peru','Nuevo Sol','PE','PER','PEN');
INSERT INTO CURRENCY VALUES ('French Polynesia','CFP Franc','PF','PYF','XPF');
INSERT INTO CURRENCY VALUES ('Papua New Guinea','Kina','PG','PNG','PGK');
INSERT INTO CURRENCY VALUES ('Philippines','Philippine Peso','PH','PHL','PHP');
INSERT INTO CURRENCY VALUES ('Pakistan','Pakistan Rupee','PK','PAK','PKR');
INSERT INTO CURRENCY VALUES ('Poland','Zloty','PL','POL','PLN');
INSERT INTO CURRENCY VALUES ('Saint Pierre And Miquelon','Euro','PM','SPM','EUR');
INSERT INTO CURRENCY VALUES ('Pitcairn','New Zealand Dollar','PN','PCN','NZD');
INSERT INTO CURRENCY VALUES ('Puerto Rico','US Dollar','PR','PRI','USD');
INSERT INTO CURRENCY VALUES ('Portugal','Euro','PT','PRT','EUR');
INSERT INTO CURRENCY VALUES ('Palau','US Dollar','PW','PLW','USD');
INSERT INTO CURRENCY VALUES ('Paraguay','Guarani','PY','PRY','PYG');
INSERT INTO CURRENCY VALUES ('Qatar','Qatari Rial','QA','QAT','QAR');
INSERT INTO CURRENCY VALUES ('Réunion','Euro','RE','REU','EUR');
INSERT INTO CURRENCY VALUES ('Romania','New Romanian Leu','RO','ROU','RON');
INSERT INTO CURRENCY VALUES ('Serbia','Serbian Dinar','RS','SRB','RSD');
INSERT INTO CURRENCY VALUES ('Russian Federation','Russian Ruble','RU','RUS','RUB');
INSERT INTO CURRENCY VALUES ('Rwanda','Rwanda Franc','RW','RWA','RWF');
INSERT INTO CURRENCY VALUES ('Saudi Arabia','Saudi Riyal','SA','SAU','SAR');
INSERT INTO CURRENCY VALUES ('Solomon Islands','Solomon Islands Dollar','SB','SLB','SBD');
INSERT INTO CURRENCY VALUES ('Seychelles','Seychelles Rupee','SC','SYC','SCR');
INSERT INTO CURRENCY VALUES ('Sudan','Sudanese Pound','SD','SDN','SDG');
INSERT INTO CURRENCY VALUES ('Sweden','Swedish Krona','SE','SWE','SEK');
INSERT INTO CURRENCY VALUES ('Singapore','Singapore Dollar','SG','SGP','SGD');
INSERT INTO CURRENCY VALUES ('Saint Helena, Ascension and Tristan Da Cunha','Saint Helena Pound','SH','SHN','SHP');
INSERT INTO CURRENCY VALUES ('Slovenia','Euro','SI','SVN','EUR');
INSERT INTO CURRENCY VALUES ('Svalbard And Jan Mayen','Norwegian Krone','SJ','SJM','NOK');
INSERT INTO CURRENCY VALUES ('Slovakia','Euro','SK','SVK','EUR');
INSERT INTO CURRENCY VALUES ('Sierra Leone','Leone','SL','SLE','SLL');
INSERT INTO CURRENCY VALUES ('San Marino','Euro','SM','SMR','EUR');
INSERT INTO CURRENCY VALUES ('Senegal','CFA Franc BCEAO','SN','SEN','XOF');
INSERT INTO CURRENCY VALUES ('Somalia','Somali Shilling','SO','SOM','SOS');
INSERT INTO CURRENCY VALUES ('Suriname','Surinam Dollar','SR','SUR','SRD');
INSERT INTO CURRENCY VALUES ('South Sudan','South Sudanese Pound','SS','SSD','SSP');
INSERT INTO CURRENCY VALUES ('Sao Tome and Principe','Dobra','ST','STP','STD');
INSERT INTO CURRENCY VALUES ('El Salvador','El Salvador Colon','SV','SLV','SVC');
INSERT INTO CURRENCY VALUES ('El Salvador','US Dollar','SV','SLV','USD');
INSERT INTO CURRENCY VALUES ('Sint Maarten (Dutch part)','Netherlands Antillean Guilder','SX','SXM','ANG');
INSERT INTO CURRENCY VALUES ('Syrian Arab Republic','Syrian Pound','SY','SYR','SYP');
INSERT INTO CURRENCY VALUES ('Swaziland','Lilangeni','SZ','SWZ','SZL');
INSERT INTO CURRENCY VALUES ('Turks and Caicos Islands','US Dollar','TC','TCA','USD');
INSERT INTO CURRENCY VALUES ('Chad','CFA Franc BEAC','TD','TCD','XAF');
INSERT INTO CURRENCY VALUES ('French Southern Territories','Euro','TF','ATF','EUR');
INSERT INTO CURRENCY VALUES ('Togo','CFA Franc BCEAO','TG','TGO','XOF');
INSERT INTO CURRENCY VALUES ('Thailand','Baht','TH','THA','THB');
INSERT INTO CURRENCY VALUES ('Tajikistan','Somoni','TJ','TJK','TJS');
INSERT INTO CURRENCY VALUES ('Tokelau','New Zealand Dollar','TK','TKL','NZD');
INSERT INTO CURRENCY VALUES ('Timor-Leste','US Dollar','TL','TLS','USD');
INSERT INTO CURRENCY VALUES ('Turkmenistan','Turkmenistan New Manat','TM','TKM','TMT');
INSERT INTO CURRENCY VALUES ('Tunisia','Tunisian Dinar','TN','TUN','TND');
INSERT INTO CURRENCY VALUES ('Tonga','Pa’anga','TO','TON','TOP');
INSERT INTO CURRENCY VALUES ('Turkey','Turkish Lira','TR','TUR','TRY');
INSERT INTO CURRENCY VALUES ('Trinidad and Tobago','Trinidad and Tobago Dollar','TT','TTO','TTD');
INSERT INTO CURRENCY VALUES ('Tuvalu','Australian Dollar','TV','TUV','AUD');
INSERT INTO CURRENCY VALUES ('Taiwan, Province Of China','New Taiwan Dollar','TW','TWN','TWD');
INSERT INTO CURRENCY VALUES ('Tanzania, United Republic of','Tanzanian Shilling','TZ','TZA','TZS');
INSERT INTO CURRENCY VALUES ('Ukraine','Hryvnia','UA','UKR','UAH');
INSERT INTO CURRENCY VALUES ('Uganda','Uganda Shilling','UG','UGA','UGX');
INSERT INTO CURRENCY VALUES ('United States Minor Outlying Islands','US Dollar','UM','UMI','USD');
INSERT INTO CURRENCY VALUES ('United States','US Dollar','US','USA','USD');
INSERT INTO CURRENCY VALUES ('United States','US Dollar (Next Day)','US','USA','USN');
INSERT INTO CURRENCY VALUES ('United States','US Dollar (Same Day)','US','USA','USS');
INSERT INTO CURRENCY VALUES ('Uruguay','Uruguay Peso en Unidades Indexadas','UY','URY','UYI');
INSERT INTO CURRENCY VALUES ('Uruguay','Peso Uruguayo','UY','URY','UYU');
INSERT INTO CURRENCY VALUES ('Uzbekistan','Uzbekistan Sum','UZ','UZB','UZS');
INSERT INTO CURRENCY VALUES ('Holy See (Vatican City State)','Euro','VA','VAT','EUR');
INSERT INTO CURRENCY VALUES ('Saint Vincent And The Grenadines','East Caribbean Dollar','VC','VCT','XCD');
INSERT INTO CURRENCY VALUES ('Venezuela, Bolivarian Republic of','Bolivar Fuerte','VE','VEN','VEF');
INSERT INTO CURRENCY VALUES ('Virgin Islands, British','US Dollar','VG','VGB','USD');
INSERT INTO CURRENCY VALUES ('Virgin Islands, U.S.','US Dollar','VI','VIR','USD');
INSERT INTO CURRENCY VALUES ('Viet Nam','Dong','VN','VNM','VND');
INSERT INTO CURRENCY VALUES ('Vanuatu','Vatu','VU','VUT','VUV');
INSERT INTO CURRENCY VALUES ('Wallis and Futuna','CFP Franc','WF','WLF','XPF');
INSERT INTO CURRENCY VALUES ('Samoa','Tala','WS','WSM','WST');
INSERT INTO CURRENCY VALUES ('Yemen','Yemeni Rial','YE','YEM','YER');
INSERT INTO CURRENCY VALUES ('Mayotte','Euro','YT','MYT','EUR');
INSERT INTO CURRENCY VALUES ('South Africa','Rand','ZA','ZAF','ZAR');
INSERT INTO CURRENCY VALUES ('Zambia','New Zambian Kwacha','ZM','ZMB','ZMW');
INSERT INTO CURRENCY VALUES ('Zimbabwe','Zimbabwe Dollar','ZW','ZWE','ZWL');
