echo "-- #!/bin/bash -e"
#!/bin/bash -e

echo "-- "

#echo "-- filein=$1"
filein=$1

#echo "-- #fileout=$2"
#fileout=$2

message=$(cat <<-'EOF'
-- The order thes insert statements need to be run in can be seen 
--  in create script or the reverse of the drop script
-- or table.order.lst

-- The order is important
-- satisfy FK constraints

-- #NB important
-- These inserts need to be fixed you need to remove the autogenerated ids 
EOF
)

echo "$message"

echo "-- "


echo -e "-- \n\n"


echo "--  "ACCOUNT"  "
grep '"ACCOUNT"' $filein 

echo "--  "CONFERENCE"  "
grep '"CONFERENCE"' $filein 

echo "--  "DEPARTMENT"  "
grep '"DEPARTMENT"' $filein 

echo "--  "ACCOUNTDEPARTMENT"  "
grep '"ACCOUNTDEPARTMENT"' $filein 

echo "--  "FOREXORDER"  "
grep '"FOREXORDER"' $filein 

echo "--  "LEAVELOOKUP"  "
grep '"LEAVELOOKUP"' $filein 

echo "--  "MOTIVATION"  "
grep '"MOTIVATION"' $filein 

echo "--  "QUOTES"  "
grep '"QUOTES"' $filein 

echo "--  "ROLE"  "
grep '"ROLE"' $filein 

echo "--  "TASK"  "
grep '"TASK"' $filein 

echo "--  "TITLE"  "
grep '"TITLE"' $filein 

echo "--  "POSITION"  "
grep '"POSITION"' $filein 

echo "--  "COUNTRY"  "
grep '"COUNTRY"' $filein 

echo "--  "REGION"  "
grep '"REGION"' $filein 

echo "--  "CITY"  "
grep '"CITY"' $filein 

echo "--  "CURRENCY"  "
grep '"CURRENCY"' $filein 

echo "--  "ACCOMODATIONQUOTES"  "
grep '"ACCOMODATIONQUOTES"' $filein 

echo "--  "CARQUOTES"  "
grep '"CARQUOTES"' $filein 

echo "--  "FLIGHTQUOTES"  "
grep '"FLIGHTQUOTES"' $filein 

echo "--  "FINALCOSTING"  "
grep '"FINALCOSTING"' $filein 

echo "--  "SESSION"  "
grep '"SESSION"' $filein 

echo "--  "TRAVELERPROFILE"  "
grep '"TRAVELERPROFILE"' $filein 

echo "--  "REWARDSPROGRAM"  "
grep '"REWARDSPROGRAM"' $filein 

echo "--  "TRAVELDOCUMENT"  "
grep '"TRAVELDOCUMENT"' $filein 

echo "--  "TRAVEL"  "
grep '"TRAVEL"' $filein 

echo "--  "ITINERARY"  "
grep '"ITINERARY"' $filein 

echo "--  "ACCOUNTROLE"  "
grep '"ACCOUNTROLE"' $filein 

echo "--  "PERMISSION"  "
grep '"PERMISSION"' $filein 

echo "--  "APPLICATION"  "
grep '"APPLICATION"' $filein 

echo "--  "APPROVAL"  "
grep '"APPROVAL"' $filein 

echo "--  "ATTACHEMENT"  "
grep '"ATTACHEMENT"' $filein 

