SET SCHEMA  "MTAMS";
--grep -i "DROP " ./mtams.create.sql | tac | cut -d" " -f2-
-- see notes in cat.script.sh for table order
-- Sepcial notes where grep does not work
-- table X comess >> after table Y

DROP TABLE  "APPROVALCHAIN";
DROP TABLE  "ATTACHEMENT";
DROP TABLE  "APPROVAL";
DROP TABLE  "APPLICATION";
DROP TABLE  "PERMISSION";
DROP TABLE  "ACCOUNTROLE";

DROP TABLE  "ITINERARY";
DROP TABLE  "TRAVEL";
DROP TABLE  "TRAVELDOCUMENT";
DROP TABLE  "REWARDSPROGRAM";
DROP TABLE  "TRAVELERPROFILE";
DROP TABLE  "SESSION";
DROP TABLE  "FLIGHTQUOTES";
DROP TABLE  "CARQUOTES";
DROP TABLE  "ACCOMODATIONQUOTES";
DROP TABLE  "FINALCOSTING";

DROP TABLE  "CURRENCY";
DROP TABLE  "CITY"; 
DROP TABLE  "REGION";
DROP TABLE  "COUNTRY";

DROP TABLE  "POSITION";
DROP TABLE  "TITLE";
DROP TABLE  "TASK";
DROP TABLE  "ROLE";
DROP TABLE  "QUOTES";
DROP TABLE  "MOTIVATION";
DROP TABLE  "LEAVELOOKUP";
DROP TABLE  "FOREXORDER";
DROP TABLE  "ACCOUNTDEPARTMENT";
DROP TABLE  "DEPARTMENT";
DROP TABLE  "MESSAGES";
DROP TABLE  "CONFERENCE";
DROP TABLE  "ACCOUNT";
DROP TABLE STAGE;


--DROP SCHEMA "MTAMS" restrict;
