-- Very basic insert script template
-- Created by Aaron
-- using squirrel sql client 
-- http://squirrel-sql.sourceforge.net/

-- There are multiple insert files, that do small increamental inserts
-- This file combines most of the inserts for the other files
-- mtams.insert.datalookup.sql  just data and lookup tables
-- mtams.insert.app.sql  just the main application

-- It will create a junk application, and all foreign keys requirements satisfied.
-- Section title APPLICATION
-- The data used is the bare minimum required for each feild.
-- This script template works to insert a single entry into most tables. 
-- To satisfy foreign key constraints you may need to change the input values where commments are shown
-- 	/* Not nullable */
-- To simplyfy this proces foreign tables names are added to the comments. 
-- For autogenerated primary keys the inserts have been modifed by removeing the primary key
-- Due to the way autogenerated primary keys work, the squence my not start at 1 if there have been failed insert attempts.

-- ******************************************************
--  DATA AND LOOKUPS
-- ******************************************************

-- The top section of inserts are conisered safe as they do not have any foreign key 
-- constraints
-- The section of inserts OTHER is unsafe and left commented
-- You can uses these inserts as templates for creating your own insert statements.
-- There is a simple application insert script to do just enough initialisation
-- of the system for most simple operations to work. It is also incomplete
-- mtams.insert.app.sql

--role inserts
--pulled down from netbeans so not optimal

--------------------------------- 
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (11, 'Applicant', DEFAULT);
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (12, 'Authorizer', DEFAULT);
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (21, 'Admin', DEFAULT);
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (22, 'SuperAdmin', DEFAULT);
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (99, 'Deactivated', DEFAULT);
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (911, 'Applicant', 'Deactivated Applicant');
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (912, 'Authorizer', 'Deactivated Authorizer');
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (921, 'Admin', 'Deactivated Admin');
INSERT INTO "ROLE" (IDROLES, "ROLE", DESCRIPTION) 
	VALUES (922, 'SuperAdmin', 'Deactivated SuperAdmin');



-- Position inserts
INSERT INTO "POSITION" (POSITION) VALUES ('Lecturer' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Professor' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Assistant Lecturer' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Tutor' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Secretary' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Head of Department' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Administrator' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Manager' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Pro vice Chancellor' /*not nullable*/);
INSERT INTO "POSITION" (POSITION) VALUES ('Chancellor' /*not nullable*/);

-- Title inserts
-- simple quick inserts
--INSERT INTO "TITLE" (TITLE) VALUES ('s' /*not nullable*/);
INSERT INTO "TITLE" (TITLE) VALUES ('Mr' /*not nullable*/);
INSERT INTO "TITLE" (TITLE) VALUES ('Mrs' /*not nullable*/);
INSERT INTO "TITLE" (TITLE) VALUES ('Miss' /*not nullable*/);
INSERT INTO "TITLE" (TITLE) VALUES ('Dr' /*not nullable*/);
INSERT INTO "TITLE" (TITLE) VALUES ('Phd' /*not nullable*/);
INSERT INTO "TITLE" (TITLE) VALUES ('Sir' /*not nullable*/);


-- Department inserts
INSERT INTO "DEPARTMENT" (DEPARTMENT) VALUES ('School of Information Technology' /*not nullable*/);
INSERT INTO "DEPARTMENT" (DEPARTMENT) VALUES ('School of Social Science' /*not nullable*/);
INSERT INTO "DEPARTMENT" (DEPARTMENT) VALUES ('Finance' /*not nullable*/);
INSERT INTO "DEPARTMENT" (DEPARTMENT) VALUES ('Administration' /*not nullable*/);
INSERT INTO "DEPARTMENT" (DEPARTMENT) VALUES ('School of Business and Economics' /*not nullable*/);
INSERT INTO "DEPARTMENT" (DEPARTMENT) VALUES ('Student Services' /*not nullable*/);
INSERT INTO "DEPARTMENT" (DEPARTMENT) VALUES ('School of Health Sciences' /*not nullable*/);
INSERT INTO "DEPARTMENT" (DEPARTMENT) VALUES ('Information Technology Services' /*not nullable*/);

-- Leave type inserts
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Annual Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Maternity Leave - Paid' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Paternity Leave - Paid' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Compassionate Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Sick Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Injury on Duty Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Conference Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Consultancy Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Research Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Long Service Leave - full pay' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Long Service Leave - half pay' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Long Service Leave - double pay' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Leave without pay' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Adoption Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Family Leave' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Outside Studies Program International' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Outside Studies Program Domestic' /*not nullable*/);
INSERT INTO "LEAVELOOKUP" (LEAVETYPE) VALUES ('Other' /*not nullable*/);


-- ******************************************************
--  APPLICATION
-- ******************************************************
--

-- 
 INSERT INTO "ACCOUNT" (USERNAME,PASSWORD,SALT,DATECREATED,DATELOGIN) VALUES ('admin' /*not nullable*/,'admin' /*not nullable*/,'s',current_timestamp,null);
 INSERT INTO "ACCOUNTROLE" (ACCOUNTID,ROLEID) VALUES (1,21);
-- select idaccount from mtams.account where username = 'admin';
 INSERT INTO "ACCOUNT" (USERNAME,PASSWORD,SALT,DATECREATED,DATELOGIN) VALUES ('super' /*not nullable*/,'super' /*not nullable*/,'s',current_timestamp,null);
 INSERT INTO "ACCOUNTROLE" (ACCOUNTID,ROLEID) VALUES (2,22);
